from tabulate import *
from BasicTypes import *
from BasicFunctions import *
def arithmeticTest():
    print("\n\tTest arithmetic:")
    def root(s):
        s.push(num_(1))
        s.Bswap()
        s.div()
        s.exp()
    s=Stack()
    v,l=[num_(0),num_(1),num_(2),num_(-2),num_(3+3j),num_(-3-3j),num_('inf'),num_('nan')],[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            s.plus()
            l[-1].append(str(s.pop()))
    print("|--------+--------+--------+--------+--------+---------+----------+-----+-----|")
    print(tabulate(l,headers=["a+b"]+v,tablefmt='orgtbl'))
    l=[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            s.minus()
            l[-1].append(str(s.pop()))
    print("|--------+--------+--------+--------+--------+---------+----------+-----+-----|")
    print(tabulate(l,headers=["a-b"]+v,tablefmt='orgtbl'))
    l=[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            s.mult()
            l[-1].append(str(s.pop()))
    print("|--------+-----+--------+--------+--------+---------+----------+-----+-----|")
    print(tabulate(l,headers=["a*b"]+v,tablefmt='orgtbl'))
    l=[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            s.div()
            s.push(num_(3))
            s.round()
            if(type(s.stack[-1])==error_ and s.stack[-1]==error_(1)):
                s.pop()
                s.pop()
            l[-1].append(str(s.pop()))
    print("|--------+-----+--------+------------+------------+----------------+----------------+-----+-----|")
    print(tabulate(l,headers=["a/b"]+v,tablefmt='orgtbl'))
    l=[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            s.exp()
            s.push(num_(3))
            s.round()
            if(type(s.stack[-1])==error_ and s.stack[-1]==error_(1)):
                s.pop()
                s.pop()
            l[-1].append(str(s.pop()))
    print("|--------+-----+--------+------+----------+------------------------+--------------------+-----+-----|")
    print(tabulate(l,headers=["a^b"]+v,tablefmt='orgtbl'))
    l=[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            root(s)
            s.push(num_(3))
            s.round()
            if(type(s.stack[-1])==error_ and s.stack[-1]==error_(1)):
                s.pop()
                s.pop()
            l[-1].append(str(s.pop()))
    print("|--------+-----+--------+---------------+---------------+---------------+---------------+-----+-----|")
    print(tabulate(l,headers=["b√a"]+v,tablefmt='orgtbl'))
    l=[]
    for i in range(len(v)):
        l.append([str(v[i])])
        for j in range(len(v)):
            s.push(v[i])
            s.push(v[j])
            s.log()
            s.push(num_(3))
            s.round()
            if(type(s.stack[-1])==error_ and s.stack[-1]==error_(1)):
                s.pop()
                s.pop()
            l[-1].append(str(s.pop()))
    print("|------------+-----+-----+---------------+---------------+--------------+--------------+-----+-----|")
    print(tabulate(l,headers=["log_b(a)"]+v,tablefmt='orgtbl'))
    l=[]
    v=[num_(pi),num_(pi/2),num_(pi/3),num_(pi/4),num_(pi/6),num_(0),num_(-pi/6*1j),num_(-pi/4*1j),num_(-pi/3*1j),num_(-pi/2*1j),num_(-pi*1j),num_('inf'),num_('nan')]
    o=[lambda s: None,lambda s: s.sin(),lambda s: s.cos(),lambda s: s.tan()]
    ao=[lambda s: None,lambda s: s.arcsin(),lambda s: s.arccos(),lambda s: s.arctan(),]
    vn=["op","π","π/2","π/3","π/4","π/6","0","-π/6*i","-π/4*i","-π/3*i","-π/2*i","-π*i","∞","∅"]
    on=["no op","sin","cos","tan"]
    aon=["no op","arcsin","arccos","arctan"]
    for i in range(1,len(o)):
        l.append([on[i]])
        for j in range(len(v)):
            s.push(v[j])
            o[i](s)
            s.push(num_(3))
            s.round()
            if(type(s.stack[-1])==error_ and s.stack[-1]==error_(1)):
                s.pop()
                s.pop()
            l[-1].append(str(s.pop()))
    print("|------+-----+-------+-------+-------+-------+-----+----------+----------+----------+----------+-----------+-----+-----|")
    print(tabulate(l,headers=vn,tablefmt='orgtbl'))
    l=[]
    for i in range(len(ao)):
        l.append([aon[i]])
        for j in range(len(v)):
            s.push(num_(v[j]))
            o[i](s)
            ao[i](s)
            s.push(num_(3))
            s.round()
            if(type(s.stack[-1])==error_ and s.stack[-1]==error_(1)):
                s.pop()
                s.pop()
            l[-1].append(str(s.pop()))
    print("Перевірка чи дорівнює arc-функції значеню яке було передано функціям:")
    print("|--------+-------+-------+--------+-------+-------+-----+----------+----------+----------+----------+----------+-----+-----|")
    print(tabulate(l,headers=vn,tablefmt='orgtbl'))
    print("Докладна перевірка tan й arctan")
    n=3
    for i in range(n*2+1):
        s.push(num_(i*pi/n-pi))
        s.push(num_(i*pi/n-pi))
        s.tan()
        s.push(num_(i*pi/n-pi))
        s.tan()
        s.arctan()
        print(f"tan(α)= {str(s.stack[-2]): <20}| {i-n: >3}*π/{n}= {str(s.stack[-3]): <20}| arctan(tan(α))= {str(s.stack[-1]): <19}")
def functionTest():
    print("\n\tTest function:")
    s=Stack()
    print(s)
    s.push({"a":[1,2,3],"b":[4,5,6],"c":[7,8,9]})
    s.push(10000000000000000+9999999999999999999999j)
    s.push("(e^π~i)")
    s.push(15)
    s.round()
    s.push("'\x00\xff⨀'")
    print(s,"push")
    s.push([0,"b",1])
    s.moveUp()
    print(s,"moveUp")
    s.push([0,"b",1])
    s.moveDown()
    print(s,"moveDown")
    s.not_()
    print(s,"not")
    s.push("'\\B12350'")
    s.push("'\\416'")
    print(s)
    s.and_()
    print(s,"and")
    s.push("'\\B12350'")
    s.push("'\\416'")
    print(s)
    s.or_()
    print(s,"or")
    s.push("'\\B12350'")
    s.push("'\\416'")
    print(s)
    s.xor()
    print(s,"xor")
    s.push(1234567890123456)
    s.push(1234567890123455)
    print(s)
    s.xor()
    print(s,"xor")
    s.random()
    s.random()
    print(s,"random")
    s.push(1j)
    s.mult()
    s.plus()
    print(s,"об'єднання чисел у комплексне")
    s.push(5)
    s.round()
    print(s,"round")
    s.abs()
    print(s,"abs")
    s.push([5,10,115])
    s.push("[bytes]")
    print(s,"push")
    s.format()
    print(s,"format")
    s.type()
    print(s,"type")
    s.push("⟨None;(2↧4~i*2√3+2^1/∞);True;'\\1\\55\\0123456789ABCDEF';\"test value()\";[False,0,\'abc\'];[0:\"0\",1:\"1\"] ;[type];{4}⟩")# ;{₴}(→ @2 @2 + P p)
    print(s,"мультиввод за допомогою ⟨;⟩ структури")
def typeTest():
    print("\n\tTest type:")
    print("Test value to str to value")
    print(none_(str_(none_(None))))
    print(num_(str_(num_(2E3+5j))))
    print(bool_(str_(bool_(True))))
    print(bytes_(str_(bytes_([0,15,255,32767]))))
    print(str_(str_(str_("abc"))))
    print(list_(str_(list_([1,2,3]))))
    print(dict_(str_(dict_({"a":1,"b":2,"c":3}))))
    # print(function_(str_(function_({₴}(5→ @2 @2 + P p)))))
    print(type_(str_(type_(num_))))
    print(error_(str_(error_(0))))
    print("Test value to python value to value")
    print(num_(complex(num_(2E3+5j))))
    print(bool_(bool(bool_(True))))
    print(bytes_(bytes(bytes_([0,15,255,32767]))))
    print(str_(str(str_("abc"))))
    print(list_(list(list_([1,2,3]))))
    print(dict_(dict(dict_({"a":1,"b":2,"c":3}))))
    print("Test empty values:",none_(""),num_(""),bool_(""),bytes_(""),str_(""),list_(""),dict_(""),type_(""),error_(""))
def containerTest():
    print("\n\tTest container:")
    s=Stack()
    s.push("⟨[bytes];[str];[list];[dict]⟩")
    print("Test write")
    s.push("⟨'abcdef';'D';3⟩")
    print(s)
    s.write()
    print(s,"write bytes_")
    s.pop()
    s.push('⟨"abcdef";"D";3⟩')
    print(s)
    s.write()
    print(s,"write str_")
    s.pop()
    s.push('⟨[3,4,5,0,1,2];9;3⟩')
    print(s)
    s.write()
    print(s,"write list_")
    s.pop()
    s.push('⟨["a":[1,2,3],"b":[4,5,6],"c":[7,8,9]];[0,False,None];"b"⟩')
    print(s)
    s.write()
    print(s,"write dict_")
    print("Test find")
    s.pop()
    s.push("⟨'abcdef';'d'⟩")
    print(s)
    s.find()
    print(s,"find bytes_")
    s.pop()
    s.pop()
    s.push('⟨"abcdef";"d"⟩')
    print(s)
    s.find()
    print(s,"find str_")
    s.pop()
    s.pop()
    s.push('⟨[3,4,5,0,1,2];2⟩')
    print(s)
    s.find()
    print(s,"find list_")
    s.pop()
    s.pop()
    s.push('⟨[0:"0",1:"1",2:"2"];"2"⟩')
    print(s)
    s.find()
    print(s,"find dict_")
    print("Test append") 
    s.pop()
    s.pop()
    s.push("⟨'abcdef';'g'⟩")
    print(s)
    s.append()
    print(s,"append bytes_")
    s.pop()
    s.push('⟨"abcdef";"g"⟩')
    print(s)
    s.append()
    print(s,"append str_")
    s.pop()
    s.push('⟨[3,4,5,0,1,2];3⟩')
    print(s)
    s.append()
    print(s,"append list_")
    print("Test delete")
    s.pop()
    s.push("⟨'abcdef';2⟩")
    print(s)
    s.delete()
    print(s,"delete bytes_")
    s.pop()
    s.push('⟨"abcdef";2⟩')
    print(s)
    s.delete()
    print(s,"delete str_")
    s.pop()
    s.push('⟨[3,4,5,0,1,2];2⟩')
    print(s)
    s.delete()
    print(s,"delete list_")
    s.pop()
    s.push('⟨[0:"0",1:"1",2:"2"];2⟩')
    print(s)
    s.delete()
    print(s,"delete dict_")
    print("Test read")
    s.pop()
    s.push("⟨'abcdef';2⟩")
    print(s)
    s.read()
    print(s,"read bytes_")
    s.pop()
    s.pop()
    s.push('⟨"abcdef";2⟩')
    print(s)
    s.read()
    print(s,"read str_")
    s.pop()
    s.pop()
    s.push('⟨[3,4,5,0,1,2];2⟩')
    print(s)
    s.read()
    print(s,"read list_")
    s.pop()
    s.pop()
    s.push('⟨[0:"0",1:"1",2:"2"];2⟩')
    print(s)
    s.read()
    print(s,"read dict_")
    print("Test len")
    s.pop()
    s.pop()
    s.push("'abcd'")
    print(s)
    s.len()
    print(s,"len bytes_")
    s.pop()
    s.push('"abcdef"')
    print(s)
    s.len()
    print(s,"len str_")
    s.pop()
    s.push("[0,1,2,3,4]")
    print(s)
    s.len()
    print(s,"len list_")
    s.pop()
    s.push('[0:"0",1:"1",2:"2"]')
    print(s)
    s.len()
    print(s,"len dict_")
    print("Test substring")
    s.pop()
    s.push("⟨'abcdef';1;4⟩")
    print(s)
    s.substring()
    print(s,"substring bytes_")
    s.pop()
    s.push('⟨"abcdef";1;4⟩')
    print(s)
    s.substring()
    print(s,"substring str_")
    s.pop()
    s.push('⟨[0,1,2,3,4,5];1;4⟩')
    print(s)
    s.substring()
    print(s,"substring list_")
    print("Test concatenate")
    s.pop()
    s.push("⟨'abcd';'klmn'⟩")
    print(s)
    s.concatenate()
    print(s,"concatenate bytes_")
    s.pop()
    s.push('⟨"abcd";"klmn"⟩')
    print(s)
    s.concatenate()
    print(s,"concatenate str_")
    s.pop()
    s.push('⟨[0,1,2];[3,4,5]⟩')
    print(s)
    s.concatenate()
    print(s,"concatenate list_")
    s.pop()
    s.push('⟨[0:"0",1:"1",2:"2"];[3:"3",4:"4",5:"5"]⟩')
    print(s)
    s.concatenate()
    print(s,"concatenate dict_")
arithmeticTest()
functionTest()
typeTest()
containerTest()